/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as ExamInfoRouteImport } from './routes/exam-info'
import { Route as CurrentAffairsRouteImport } from './routes/current-affairs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamsSlugRouteImport } from './routes/exams.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedTestTestIdRouteImport } from './routes/_authenticated/test.$testId'
import { Route as AuthenticatedResultAttemptIdRouteImport } from './routes/_authenticated/result.$attemptId'
import { Route as AuthenticatedDashboardRankRouteImport } from './routes/_authenticated/dashboard.rank'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardPreviousYearPapersRouteImport } from './routes/_authenticated/dashboard.previous-year-papers'
import { Route as AuthenticatedDashboardMockTestsRouteImport } from './routes/_authenticated/dashboard.mock-tests'
import { Route as AuthenticatedDashboardExamAlertsRouteImport } from './routes/_authenticated/dashboard.exam-alerts'
import { Route as AuthenticatedDashboardCurrentAffairsRouteImport } from './routes/_authenticated/dashboard.current-affairs'
import { Route as AuthenticatedDashboardAttemptedTestsRouteImport } from './routes/_authenticated/dashboard.attempted-tests'
import { Route as AuthenticatedDashboardAnswerKeyRouteImport } from './routes/_authenticated/dashboard.answer-key'

const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamInfoRoute = ExamInfoRouteImport.update({
  id: '/exam-info',
  path: '/exam-info',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentAffairsRoute = CurrentAffairsRouteImport.update({
  id: '/current-affairs',
  path: '/current-affairs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsSlugRoute = ExamsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExamsRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedTestTestIdRoute = AuthenticatedTestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultAttemptIdRoute =
  AuthenticatedResultAttemptIdRouteImport.update({
    id: '/result/$attemptId',
    path: '/result/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRankRoute =
  AuthenticatedDashboardRankRouteImport.update({
    id: '/rank',
    path: '/rank',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPreviousYearPapersRoute =
  AuthenticatedDashboardPreviousYearPapersRouteImport.update({
    id: '/previous-year-papers',
    path: '/previous-year-papers',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMockTestsRoute =
  AuthenticatedDashboardMockTestsRouteImport.update({
    id: '/mock-tests',
    path: '/mock-tests',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardExamAlertsRoute =
  AuthenticatedDashboardExamAlertsRouteImport.update({
    id: '/exam-alerts',
    path: '/exam-alerts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCurrentAffairsRoute =
  AuthenticatedDashboardCurrentAffairsRouteImport.update({
    id: '/current-affairs',
    path: '/current-affairs',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAttemptedTestsRoute =
  AuthenticatedDashboardAttemptedTestsRouteImport.update({
    id: '/attempted-tests',
    path: '/attempted-tests',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnswerKeyRoute =
  AuthenticatedDashboardAnswerKeyRouteImport.update({
    id: '/answer-key',
    path: '/answer-key',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/auth': typeof AuthRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/exam-info': typeof ExamInfoRoute
  '/exams': typeof ExamsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/exams/$slug': typeof ExamsSlugRoute
  '/dashboard/answer-key': typeof AuthenticatedDashboardAnswerKeyRoute
  '/dashboard/attempted-tests': typeof AuthenticatedDashboardAttemptedTestsRoute
  '/dashboard/current-affairs': typeof AuthenticatedDashboardCurrentAffairsRoute
  '/dashboard/exam-alerts': typeof AuthenticatedDashboardExamAlertsRoute
  '/dashboard/mock-tests': typeof AuthenticatedDashboardMockTestsRoute
  '/dashboard/previous-year-papers': typeof AuthenticatedDashboardPreviousYearPapersRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/rank': typeof AuthenticatedDashboardRankRoute
  '/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/test/$testId': typeof AuthenticatedTestTestIdRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/auth': typeof AuthRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/exam-info': typeof ExamInfoRoute
  '/exams': typeof ExamsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/dashboard/answer-key': typeof AuthenticatedDashboardAnswerKeyRoute
  '/dashboard/attempted-tests': typeof AuthenticatedDashboardAttemptedTestsRoute
  '/dashboard/current-affairs': typeof AuthenticatedDashboardCurrentAffairsRoute
  '/dashboard/exam-alerts': typeof AuthenticatedDashboardExamAlertsRoute
  '/dashboard/mock-tests': typeof AuthenticatedDashboardMockTestsRoute
  '/dashboard/previous-year-papers': typeof AuthenticatedDashboardPreviousYearPapersRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/rank': typeof AuthenticatedDashboardRankRoute
  '/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/test/$testId': typeof AuthenticatedTestTestIdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/auth': typeof AuthRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/exam-info': typeof ExamInfoRoute
  '/exams': typeof ExamsRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/exams/$slug': typeof ExamsSlugRoute
  '/_authenticated/dashboard/answer-key': typeof AuthenticatedDashboardAnswerKeyRoute
  '/_authenticated/dashboard/attempted-tests': typeof AuthenticatedDashboardAttemptedTestsRoute
  '/_authenticated/dashboard/current-affairs': typeof AuthenticatedDashboardCurrentAffairsRoute
  '/_authenticated/dashboard/exam-alerts': typeof AuthenticatedDashboardExamAlertsRoute
  '/_authenticated/dashboard/mock-tests': typeof AuthenticatedDashboardMockTestsRoute
  '/_authenticated/dashboard/previous-year-papers': typeof AuthenticatedDashboardPreviousYearPapersRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/rank': typeof AuthenticatedDashboardRankRoute
  '/_authenticated/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/_authenticated/test/$testId': typeof AuthenticatedTestTestIdRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/auth'
    | '/current-affairs'
    | '/exam-info'
    | '/exams'
    | '/admin'
    | '/dashboard'
    | '/exams/$slug'
    | '/dashboard/answer-key'
    | '/dashboard/attempted-tests'
    | '/dashboard/current-affairs'
    | '/dashboard/exam-alerts'
    | '/dashboard/mock-tests'
    | '/dashboard/previous-year-papers'
    | '/dashboard/profile'
    | '/dashboard/rank'
    | '/result/$attemptId'
    | '/test/$testId'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/auth'
    | '/current-affairs'
    | '/exam-info'
    | '/exams'
    | '/admin'
    | '/exams/$slug'
    | '/dashboard/answer-key'
    | '/dashboard/attempted-tests'
    | '/dashboard/current-affairs'
    | '/dashboard/exam-alerts'
    | '/dashboard/mock-tests'
    | '/dashboard/previous-year-papers'
    | '/dashboard/profile'
    | '/dashboard/rank'
    | '/result/$attemptId'
    | '/test/$testId'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about-us'
    | '/auth'
    | '/current-affairs'
    | '/exam-info'
    | '/exams'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/exams/$slug'
    | '/_authenticated/dashboard/answer-key'
    | '/_authenticated/dashboard/attempted-tests'
    | '/_authenticated/dashboard/current-affairs'
    | '/_authenticated/dashboard/exam-alerts'
    | '/_authenticated/dashboard/mock-tests'
    | '/_authenticated/dashboard/previous-year-papers'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/rank'
    | '/_authenticated/result/$attemptId'
    | '/_authenticated/test/$testId'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutUsRoute: typeof AboutUsRoute
  AuthRoute: typeof AuthRoute
  CurrentAffairsRoute: typeof CurrentAffairsRoute
  ExamInfoRoute: typeof ExamInfoRoute
  ExamsRoute: typeof ExamsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-info': {
      id: '/exam-info'
      path: '/exam-info'
      fullPath: '/exam-info'
      preLoaderRoute: typeof ExamInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-affairs': {
      id: '/current-affairs'
      path: '/current-affairs'
      fullPath: '/current-affairs'
      preLoaderRoute: typeof CurrentAffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$slug': {
      id: '/exams/$slug'
      path: '/$slug'
      fullPath: '/exams/$slug'
      preLoaderRoute: typeof ExamsSlugRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/test/$testId': {
      id: '/_authenticated/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof AuthenticatedTestTestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/result/$attemptId': {
      id: '/_authenticated/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/result/$attemptId'
      preLoaderRoute: typeof AuthenticatedResultAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/rank': {
      id: '/_authenticated/dashboard/rank'
      path: '/rank'
      fullPath: '/dashboard/rank'
      preLoaderRoute: typeof AuthenticatedDashboardRankRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/previous-year-papers': {
      id: '/_authenticated/dashboard/previous-year-papers'
      path: '/previous-year-papers'
      fullPath: '/dashboard/previous-year-papers'
      preLoaderRoute: typeof AuthenticatedDashboardPreviousYearPapersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/mock-tests': {
      id: '/_authenticated/dashboard/mock-tests'
      path: '/mock-tests'
      fullPath: '/dashboard/mock-tests'
      preLoaderRoute: typeof AuthenticatedDashboardMockTestsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/exam-alerts': {
      id: '/_authenticated/dashboard/exam-alerts'
      path: '/exam-alerts'
      fullPath: '/dashboard/exam-alerts'
      preLoaderRoute: typeof AuthenticatedDashboardExamAlertsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/current-affairs': {
      id: '/_authenticated/dashboard/current-affairs'
      path: '/current-affairs'
      fullPath: '/dashboard/current-affairs'
      preLoaderRoute: typeof AuthenticatedDashboardCurrentAffairsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/attempted-tests': {
      id: '/_authenticated/dashboard/attempted-tests'
      path: '/attempted-tests'
      fullPath: '/dashboard/attempted-tests'
      preLoaderRoute: typeof AuthenticatedDashboardAttemptedTestsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/answer-key': {
      id: '/_authenticated/dashboard/answer-key'
      path: '/answer-key'
      fullPath: '/dashboard/answer-key'
      preLoaderRoute: typeof AuthenticatedDashboardAnswerKeyRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAnswerKeyRoute: typeof AuthenticatedDashboardAnswerKeyRoute
  AuthenticatedDashboardAttemptedTestsRoute: typeof AuthenticatedDashboardAttemptedTestsRoute
  AuthenticatedDashboardCurrentAffairsRoute: typeof AuthenticatedDashboardCurrentAffairsRoute
  AuthenticatedDashboardExamAlertsRoute: typeof AuthenticatedDashboardExamAlertsRoute
  AuthenticatedDashboardMockTestsRoute: typeof AuthenticatedDashboardMockTestsRoute
  AuthenticatedDashboardPreviousYearPapersRoute: typeof AuthenticatedDashboardPreviousYearPapersRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardRankRoute: typeof AuthenticatedDashboardRankRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAnswerKeyRoute: AuthenticatedDashboardAnswerKeyRoute,
    AuthenticatedDashboardAttemptedTestsRoute:
      AuthenticatedDashboardAttemptedTestsRoute,
    AuthenticatedDashboardCurrentAffairsRoute:
      AuthenticatedDashboardCurrentAffairsRoute,
    AuthenticatedDashboardExamAlertsRoute:
      AuthenticatedDashboardExamAlertsRoute,
    AuthenticatedDashboardMockTestsRoute: AuthenticatedDashboardMockTestsRoute,
    AuthenticatedDashboardPreviousYearPapersRoute:
      AuthenticatedDashboardPreviousYearPapersRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardRankRoute: AuthenticatedDashboardRankRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedResultAttemptIdRoute: typeof AuthenticatedResultAttemptIdRoute
  AuthenticatedTestTestIdRoute: typeof AuthenticatedTestTestIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedResultAttemptIdRoute: AuthenticatedResultAttemptIdRoute,
  AuthenticatedTestTestIdRoute: AuthenticatedTestTestIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ExamsRouteChildren {
  ExamsSlugRoute: typeof ExamsSlugRoute
}

const ExamsRouteChildren: ExamsRouteChildren = {
  ExamsSlugRoute: ExamsSlugRoute,
}

const ExamsRouteWithChildren = ExamsRoute._addFileChildren(ExamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutUsRoute: AboutUsRoute,
  AuthRoute: AuthRoute,
  CurrentAffairsRoute: CurrentAffairsRoute,
  ExamInfoRoute: ExamInfoRoute,
  ExamsRoute: ExamsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
