/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as ExamInfoRouteImport } from './routes/exam-info'
import { Route as CurrentAffairsRouteImport } from './routes/current-affairs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin-dashboard.index'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as ExamsSlugRouteImport } from './routes/exams.$slug'
import { Route as CurrentAffairsIdRouteImport } from './routes/current-affairs.$id'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AdminDashboardUsersRouteImport } from './routes/admin-dashboard.users'
import { Route as AdminDashboardTestsRouteImport } from './routes/admin-dashboard.tests'
import { Route as AdminDashboardTestSeriesRouteImport } from './routes/admin-dashboard.test-series'
import { Route as AdminDashboardSettingsRouteImport } from './routes/admin-dashboard.settings'
import { Route as AdminDashboardReportsRouteImport } from './routes/admin-dashboard.reports'
import { Route as AdminDashboardQuestionsRouteImport } from './routes/admin-dashboard.questions'
import { Route as AdminDashboardProfileRouteImport } from './routes/admin-dashboard.profile'
import { Route as AdminDashboardPagesRouteImport } from './routes/admin-dashboard.pages'
import { Route as AdminDashboardNotificationsRouteImport } from './routes/admin-dashboard.notifications'
import { Route as AdminDashboardMediaRouteImport } from './routes/admin-dashboard.media'
import { Route as AdminDashboardCurrentAffairsRouteImport } from './routes/admin-dashboard.current-affairs'
import { Route as AdminDashboardCategoriesRouteImport } from './routes/admin-dashboard.categories'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedTestTestIdRouteImport } from './routes/_authenticated/test.$testId'
import { Route as AuthenticatedResultAttemptIdRouteImport } from './routes/_authenticated/result.$attemptId'
import { Route as AuthenticatedDashboardRankRouteImport } from './routes/_authenticated/dashboard.rank'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardPreviousYearPapersRouteImport } from './routes/_authenticated/dashboard.previous-year-papers'
import { Route as AuthenticatedDashboardOverviewRouteImport } from './routes/_authenticated/dashboard.overview'
import { Route as AuthenticatedDashboardMockTestsRouteImport } from './routes/_authenticated/dashboard.mock-tests'
import { Route as AuthenticatedDashboardExamAlertsRouteImport } from './routes/_authenticated/dashboard.exam-alerts'
import { Route as AuthenticatedDashboardCurrentAffairsRouteImport } from './routes/_authenticated/dashboard.current-affairs'
import { Route as AuthenticatedDashboardAttemptedTestsRouteImport } from './routes/_authenticated/dashboard.attempted-tests'
import { Route as AuthenticatedDashboardAnswerKeyRouteImport } from './routes/_authenticated/dashboard.answer-key'
import { Route as AuthenticatedDashboardTestSeriesIdRouteImport } from './routes/_authenticated/dashboard.test-series.$id'
import { Route as AuthenticatedDashboardCurrentAffairsIdRouteImport } from './routes/_authenticated/dashboard.current-affairs.$id'

const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamInfoRoute = ExamInfoRouteImport.update({
  id: '/exam-info',
  path: '/exam-info',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentAffairsRoute = CurrentAffairsRouteImport.update({
  id: '/current-affairs',
  path: '/current-affairs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsSlugRoute = ExamsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExamsRoute,
} as any)
const CurrentAffairsIdRoute = CurrentAffairsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CurrentAffairsRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdminDashboardUsersRoute = AdminDashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardTestsRoute = AdminDashboardTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardTestSeriesRoute =
  AdminDashboardTestSeriesRouteImport.update({
    id: '/test-series',
    path: '/test-series',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardSettingsRoute = AdminDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardReportsRoute = AdminDashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardQuestionsRoute = AdminDashboardQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardProfileRoute = AdminDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardPagesRoute = AdminDashboardPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardNotificationsRoute =
  AdminDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardMediaRoute = AdminDashboardMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardCurrentAffairsRoute =
  AdminDashboardCurrentAffairsRouteImport.update({
    id: '/current-affairs',
    path: '/current-affairs',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardCategoriesRoute =
  AdminDashboardCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedTestTestIdRoute = AuthenticatedTestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultAttemptIdRoute =
  AuthenticatedResultAttemptIdRouteImport.update({
    id: '/result/$attemptId',
    path: '/result/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRankRoute =
  AuthenticatedDashboardRankRouteImport.update({
    id: '/rank',
    path: '/rank',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPreviousYearPapersRoute =
  AuthenticatedDashboardPreviousYearPapersRouteImport.update({
    id: '/previous-year-papers',
    path: '/previous-year-papers',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOverviewRoute =
  AuthenticatedDashboardOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMockTestsRoute =
  AuthenticatedDashboardMockTestsRouteImport.update({
    id: '/mock-tests',
    path: '/mock-tests',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardExamAlertsRoute =
  AuthenticatedDashboardExamAlertsRouteImport.update({
    id: '/exam-alerts',
    path: '/exam-alerts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCurrentAffairsRoute =
  AuthenticatedDashboardCurrentAffairsRouteImport.update({
    id: '/current-affairs',
    path: '/current-affairs',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAttemptedTestsRoute =
  AuthenticatedDashboardAttemptedTestsRouteImport.update({
    id: '/attempted-tests',
    path: '/attempted-tests',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnswerKeyRoute =
  AuthenticatedDashboardAnswerKeyRouteImport.update({
    id: '/answer-key',
    path: '/answer-key',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTestSeriesIdRoute =
  AuthenticatedDashboardTestSeriesIdRouteImport.update({
    id: '/test-series/$id',
    path: '/test-series/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCurrentAffairsIdRoute =
  AuthenticatedDashboardCurrentAffairsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardCurrentAffairsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin-dashboard': typeof AdminDashboardRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRouteWithChildren
  '/current-affairs': typeof CurrentAffairsRouteWithChildren
  '/exam-info': typeof ExamInfoRoute
  '/exams': typeof ExamsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/admin-dashboard/categories': typeof AdminDashboardCategoriesRoute
  '/admin-dashboard/current-affairs': typeof AdminDashboardCurrentAffairsRoute
  '/admin-dashboard/media': typeof AdminDashboardMediaRoute
  '/admin-dashboard/notifications': typeof AdminDashboardNotificationsRoute
  '/admin-dashboard/pages': typeof AdminDashboardPagesRoute
  '/admin-dashboard/profile': typeof AdminDashboardProfileRoute
  '/admin-dashboard/questions': typeof AdminDashboardQuestionsRoute
  '/admin-dashboard/reports': typeof AdminDashboardReportsRoute
  '/admin-dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin-dashboard/test-series': typeof AdminDashboardTestSeriesRoute
  '/admin-dashboard/tests': typeof AdminDashboardTestsRoute
  '/admin-dashboard/users': typeof AdminDashboardUsersRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/current-affairs/$id': typeof CurrentAffairsIdRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/admin-dashboard/': typeof AdminDashboardIndexRoute
  '/dashboard/answer-key': typeof AuthenticatedDashboardAnswerKeyRoute
  '/dashboard/attempted-tests': typeof AuthenticatedDashboardAttemptedTestsRoute
  '/dashboard/current-affairs': typeof AuthenticatedDashboardCurrentAffairsRouteWithChildren
  '/dashboard/exam-alerts': typeof AuthenticatedDashboardExamAlertsRoute
  '/dashboard/mock-tests': typeof AuthenticatedDashboardMockTestsRoute
  '/dashboard/overview': typeof AuthenticatedDashboardOverviewRoute
  '/dashboard/previous-year-papers': typeof AuthenticatedDashboardPreviousYearPapersRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/rank': typeof AuthenticatedDashboardRankRoute
  '/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/test/$testId': typeof AuthenticatedTestTestIdRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/current-affairs/$id': typeof AuthenticatedDashboardCurrentAffairsIdRoute
  '/dashboard/test-series/$id': typeof AuthenticatedDashboardTestSeriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRouteWithChildren
  '/current-affairs': typeof CurrentAffairsRouteWithChildren
  '/exam-info': typeof ExamInfoRoute
  '/exams': typeof ExamsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-dashboard/categories': typeof AdminDashboardCategoriesRoute
  '/admin-dashboard/current-affairs': typeof AdminDashboardCurrentAffairsRoute
  '/admin-dashboard/media': typeof AdminDashboardMediaRoute
  '/admin-dashboard/notifications': typeof AdminDashboardNotificationsRoute
  '/admin-dashboard/pages': typeof AdminDashboardPagesRoute
  '/admin-dashboard/profile': typeof AdminDashboardProfileRoute
  '/admin-dashboard/questions': typeof AdminDashboardQuestionsRoute
  '/admin-dashboard/reports': typeof AdminDashboardReportsRoute
  '/admin-dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin-dashboard/test-series': typeof AdminDashboardTestSeriesRoute
  '/admin-dashboard/tests': typeof AdminDashboardTestsRoute
  '/admin-dashboard/users': typeof AdminDashboardUsersRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/current-affairs/$id': typeof CurrentAffairsIdRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/admin-dashboard': typeof AdminDashboardIndexRoute
  '/dashboard/answer-key': typeof AuthenticatedDashboardAnswerKeyRoute
  '/dashboard/attempted-tests': typeof AuthenticatedDashboardAttemptedTestsRoute
  '/dashboard/current-affairs': typeof AuthenticatedDashboardCurrentAffairsRouteWithChildren
  '/dashboard/exam-alerts': typeof AuthenticatedDashboardExamAlertsRoute
  '/dashboard/mock-tests': typeof AuthenticatedDashboardMockTestsRoute
  '/dashboard/overview': typeof AuthenticatedDashboardOverviewRoute
  '/dashboard/previous-year-papers': typeof AuthenticatedDashboardPreviousYearPapersRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/rank': typeof AuthenticatedDashboardRankRoute
  '/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/test/$testId': typeof AuthenticatedTestTestIdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/current-affairs/$id': typeof AuthenticatedDashboardCurrentAffairsIdRoute
  '/dashboard/test-series/$id': typeof AuthenticatedDashboardTestSeriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/admin-dashboard': typeof AdminDashboardRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRouteWithChildren
  '/current-affairs': typeof CurrentAffairsRouteWithChildren
  '/exam-info': typeof ExamInfoRoute
  '/exams': typeof ExamsRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/admin-dashboard/categories': typeof AdminDashboardCategoriesRoute
  '/admin-dashboard/current-affairs': typeof AdminDashboardCurrentAffairsRoute
  '/admin-dashboard/media': typeof AdminDashboardMediaRoute
  '/admin-dashboard/notifications': typeof AdminDashboardNotificationsRoute
  '/admin-dashboard/pages': typeof AdminDashboardPagesRoute
  '/admin-dashboard/profile': typeof AdminDashboardProfileRoute
  '/admin-dashboard/questions': typeof AdminDashboardQuestionsRoute
  '/admin-dashboard/reports': typeof AdminDashboardReportsRoute
  '/admin-dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin-dashboard/test-series': typeof AdminDashboardTestSeriesRoute
  '/admin-dashboard/tests': typeof AdminDashboardTestsRoute
  '/admin-dashboard/users': typeof AdminDashboardUsersRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/current-affairs/$id': typeof CurrentAffairsIdRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/admin-dashboard/': typeof AdminDashboardIndexRoute
  '/_authenticated/dashboard/answer-key': typeof AuthenticatedDashboardAnswerKeyRoute
  '/_authenticated/dashboard/attempted-tests': typeof AuthenticatedDashboardAttemptedTestsRoute
  '/_authenticated/dashboard/current-affairs': typeof AuthenticatedDashboardCurrentAffairsRouteWithChildren
  '/_authenticated/dashboard/exam-alerts': typeof AuthenticatedDashboardExamAlertsRoute
  '/_authenticated/dashboard/mock-tests': typeof AuthenticatedDashboardMockTestsRoute
  '/_authenticated/dashboard/overview': typeof AuthenticatedDashboardOverviewRoute
  '/_authenticated/dashboard/previous-year-papers': typeof AuthenticatedDashboardPreviousYearPapersRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/rank': typeof AuthenticatedDashboardRankRoute
  '/_authenticated/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/_authenticated/test/$testId': typeof AuthenticatedTestTestIdRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/current-affairs/$id': typeof AuthenticatedDashboardCurrentAffairsIdRoute
  '/_authenticated/dashboard/test-series/$id': typeof AuthenticatedDashboardTestSeriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/admin-dashboard'
    | '/admin-login'
    | '/auth'
    | '/current-affairs'
    | '/exam-info'
    | '/exams'
    | '/admin'
    | '/dashboard'
    | '/admin-dashboard/categories'
    | '/admin-dashboard/current-affairs'
    | '/admin-dashboard/media'
    | '/admin-dashboard/notifications'
    | '/admin-dashboard/pages'
    | '/admin-dashboard/profile'
    | '/admin-dashboard/questions'
    | '/admin-dashboard/reports'
    | '/admin-dashboard/settings'
    | '/admin-dashboard/test-series'
    | '/admin-dashboard/tests'
    | '/admin-dashboard/users'
    | '/auth/reset-password'
    | '/current-affairs/$id'
    | '/exams/$slug'
    | '/pages/$slug'
    | '/admin-dashboard/'
    | '/dashboard/answer-key'
    | '/dashboard/attempted-tests'
    | '/dashboard/current-affairs'
    | '/dashboard/exam-alerts'
    | '/dashboard/mock-tests'
    | '/dashboard/overview'
    | '/dashboard/previous-year-papers'
    | '/dashboard/profile'
    | '/dashboard/rank'
    | '/result/$attemptId'
    | '/test/$testId'
    | '/dashboard/'
    | '/dashboard/current-affairs/$id'
    | '/dashboard/test-series/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/admin-login'
    | '/auth'
    | '/current-affairs'
    | '/exam-info'
    | '/exams'
    | '/admin'
    | '/admin-dashboard/categories'
    | '/admin-dashboard/current-affairs'
    | '/admin-dashboard/media'
    | '/admin-dashboard/notifications'
    | '/admin-dashboard/pages'
    | '/admin-dashboard/profile'
    | '/admin-dashboard/questions'
    | '/admin-dashboard/reports'
    | '/admin-dashboard/settings'
    | '/admin-dashboard/test-series'
    | '/admin-dashboard/tests'
    | '/admin-dashboard/users'
    | '/auth/reset-password'
    | '/current-affairs/$id'
    | '/exams/$slug'
    | '/pages/$slug'
    | '/admin-dashboard'
    | '/dashboard/answer-key'
    | '/dashboard/attempted-tests'
    | '/dashboard/current-affairs'
    | '/dashboard/exam-alerts'
    | '/dashboard/mock-tests'
    | '/dashboard/overview'
    | '/dashboard/previous-year-papers'
    | '/dashboard/profile'
    | '/dashboard/rank'
    | '/result/$attemptId'
    | '/test/$testId'
    | '/dashboard'
    | '/dashboard/current-affairs/$id'
    | '/dashboard/test-series/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about-us'
    | '/admin-dashboard'
    | '/admin-login'
    | '/auth'
    | '/current-affairs'
    | '/exam-info'
    | '/exams'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/admin-dashboard/categories'
    | '/admin-dashboard/current-affairs'
    | '/admin-dashboard/media'
    | '/admin-dashboard/notifications'
    | '/admin-dashboard/pages'
    | '/admin-dashboard/profile'
    | '/admin-dashboard/questions'
    | '/admin-dashboard/reports'
    | '/admin-dashboard/settings'
    | '/admin-dashboard/test-series'
    | '/admin-dashboard/tests'
    | '/admin-dashboard/users'
    | '/auth/reset-password'
    | '/current-affairs/$id'
    | '/exams/$slug'
    | '/pages/$slug'
    | '/admin-dashboard/'
    | '/_authenticated/dashboard/answer-key'
    | '/_authenticated/dashboard/attempted-tests'
    | '/_authenticated/dashboard/current-affairs'
    | '/_authenticated/dashboard/exam-alerts'
    | '/_authenticated/dashboard/mock-tests'
    | '/_authenticated/dashboard/overview'
    | '/_authenticated/dashboard/previous-year-papers'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/rank'
    | '/_authenticated/result/$attemptId'
    | '/_authenticated/test/$testId'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/current-affairs/$id'
    | '/_authenticated/dashboard/test-series/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutUsRoute: typeof AboutUsRoute
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRouteWithChildren
  CurrentAffairsRoute: typeof CurrentAffairsRouteWithChildren
  ExamInfoRoute: typeof ExamInfoRoute
  ExamsRoute: typeof ExamsRouteWithChildren
  PagesSlugRoute: typeof PagesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-info': {
      id: '/exam-info'
      path: '/exam-info'
      fullPath: '/exam-info'
      preLoaderRoute: typeof ExamInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-affairs': {
      id: '/current-affairs'
      path: '/current-affairs'
      fullPath: '/current-affairs'
      preLoaderRoute: typeof CurrentAffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard/': {
      id: '/admin-dashboard/'
      path: '/'
      fullPath: '/admin-dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$slug': {
      id: '/exams/$slug'
      path: '/$slug'
      fullPath: '/exams/$slug'
      preLoaderRoute: typeof ExamsSlugRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/current-affairs/$id': {
      id: '/current-affairs/$id'
      path: '/$id'
      fullPath: '/current-affairs/$id'
      preLoaderRoute: typeof CurrentAffairsIdRouteImport
      parentRoute: typeof CurrentAffairsRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin-dashboard/users': {
      id: '/admin-dashboard/users'
      path: '/users'
      fullPath: '/admin-dashboard/users'
      preLoaderRoute: typeof AdminDashboardUsersRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin-dashboard/tests': {
      id: '/admin-dashboard/tests'
      path: '/tests'
      fullPath: '/admin-dashboard/tests'
      preLoaderRoute: typeof AdminDashboardTestsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin-dashboard/test-series': {
      id: '/admin-dashboard/test-series'
      path: '/test-series'
      fullPath: '/admin-dashboard/test-series'
      preLoaderRoute: typeof AdminDashboardTestSeriesRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin-dashboard/settings': {
      id: '/admin-dashboard/settings'
      path: '/settings'
      fullPath: '/admin-dashboard/settings'
      preLoaderRoute: typeof AdminDashboardSettingsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin-dashboard/reports': {
      id: '/admin-dashboard/reports'
      path: '/reports'
      fullPath: '/admin-dashboard/reports'
      preLoaderRoute: typeof AdminDashboardReportsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin-dashboard/questions': {
      id: '/admin-dashboard/questions'
      path: '/questions'
      fullPath: '/admin-dashboard/questions'
      preLoaderRoute: typeof AdminDashboardQuestionsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin-dashboard/profile': {
      id: '/admin-dashboard/profile'
      path: '/profile'
      fullPath: '/admin-dashboard/profile'
      preLoaderRoute: typeof AdminDashboardProfileRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin-dashboard/pages': {
      id: '/admin-dashboard/pages'
      path: '/pages'
      fullPath: '/admin-dashboard/pages'
      preLoaderRoute: typeof AdminDashboardPagesRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin-dashboard/notifications': {
      id: '/admin-dashboard/notifications'
      path: '/notifications'
      fullPath: '/admin-dashboard/notifications'
      preLoaderRoute: typeof AdminDashboardNotificationsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin-dashboard/media': {
      id: '/admin-dashboard/media'
      path: '/media'
      fullPath: '/admin-dashboard/media'
      preLoaderRoute: typeof AdminDashboardMediaRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin-dashboard/current-affairs': {
      id: '/admin-dashboard/current-affairs'
      path: '/current-affairs'
      fullPath: '/admin-dashboard/current-affairs'
      preLoaderRoute: typeof AdminDashboardCurrentAffairsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin-dashboard/categories': {
      id: '/admin-dashboard/categories'
      path: '/categories'
      fullPath: '/admin-dashboard/categories'
      preLoaderRoute: typeof AdminDashboardCategoriesRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/test/$testId': {
      id: '/_authenticated/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof AuthenticatedTestTestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/result/$attemptId': {
      id: '/_authenticated/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/result/$attemptId'
      preLoaderRoute: typeof AuthenticatedResultAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/rank': {
      id: '/_authenticated/dashboard/rank'
      path: '/rank'
      fullPath: '/dashboard/rank'
      preLoaderRoute: typeof AuthenticatedDashboardRankRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/previous-year-papers': {
      id: '/_authenticated/dashboard/previous-year-papers'
      path: '/previous-year-papers'
      fullPath: '/dashboard/previous-year-papers'
      preLoaderRoute: typeof AuthenticatedDashboardPreviousYearPapersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/overview': {
      id: '/_authenticated/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof AuthenticatedDashboardOverviewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/mock-tests': {
      id: '/_authenticated/dashboard/mock-tests'
      path: '/mock-tests'
      fullPath: '/dashboard/mock-tests'
      preLoaderRoute: typeof AuthenticatedDashboardMockTestsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/exam-alerts': {
      id: '/_authenticated/dashboard/exam-alerts'
      path: '/exam-alerts'
      fullPath: '/dashboard/exam-alerts'
      preLoaderRoute: typeof AuthenticatedDashboardExamAlertsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/current-affairs': {
      id: '/_authenticated/dashboard/current-affairs'
      path: '/current-affairs'
      fullPath: '/dashboard/current-affairs'
      preLoaderRoute: typeof AuthenticatedDashboardCurrentAffairsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/attempted-tests': {
      id: '/_authenticated/dashboard/attempted-tests'
      path: '/attempted-tests'
      fullPath: '/dashboard/attempted-tests'
      preLoaderRoute: typeof AuthenticatedDashboardAttemptedTestsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/answer-key': {
      id: '/_authenticated/dashboard/answer-key'
      path: '/answer-key'
      fullPath: '/dashboard/answer-key'
      preLoaderRoute: typeof AuthenticatedDashboardAnswerKeyRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/test-series/$id': {
      id: '/_authenticated/dashboard/test-series/$id'
      path: '/test-series/$id'
      fullPath: '/dashboard/test-series/$id'
      preLoaderRoute: typeof AuthenticatedDashboardTestSeriesIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/current-affairs/$id': {
      id: '/_authenticated/dashboard/current-affairs/$id'
      path: '/$id'
      fullPath: '/dashboard/current-affairs/$id'
      preLoaderRoute: typeof AuthenticatedDashboardCurrentAffairsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardCurrentAffairsRoute
    }
  }
}

interface AuthenticatedDashboardCurrentAffairsRouteChildren {
  AuthenticatedDashboardCurrentAffairsIdRoute: typeof AuthenticatedDashboardCurrentAffairsIdRoute
}

const AuthenticatedDashboardCurrentAffairsRouteChildren: AuthenticatedDashboardCurrentAffairsRouteChildren =
  {
    AuthenticatedDashboardCurrentAffairsIdRoute:
      AuthenticatedDashboardCurrentAffairsIdRoute,
  }

const AuthenticatedDashboardCurrentAffairsRouteWithChildren =
  AuthenticatedDashboardCurrentAffairsRoute._addFileChildren(
    AuthenticatedDashboardCurrentAffairsRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAnswerKeyRoute: typeof AuthenticatedDashboardAnswerKeyRoute
  AuthenticatedDashboardAttemptedTestsRoute: typeof AuthenticatedDashboardAttemptedTestsRoute
  AuthenticatedDashboardCurrentAffairsRoute: typeof AuthenticatedDashboardCurrentAffairsRouteWithChildren
  AuthenticatedDashboardExamAlertsRoute: typeof AuthenticatedDashboardExamAlertsRoute
  AuthenticatedDashboardMockTestsRoute: typeof AuthenticatedDashboardMockTestsRoute
  AuthenticatedDashboardOverviewRoute: typeof AuthenticatedDashboardOverviewRoute
  AuthenticatedDashboardPreviousYearPapersRoute: typeof AuthenticatedDashboardPreviousYearPapersRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardRankRoute: typeof AuthenticatedDashboardRankRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardTestSeriesIdRoute: typeof AuthenticatedDashboardTestSeriesIdRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAnswerKeyRoute: AuthenticatedDashboardAnswerKeyRoute,
    AuthenticatedDashboardAttemptedTestsRoute:
      AuthenticatedDashboardAttemptedTestsRoute,
    AuthenticatedDashboardCurrentAffairsRoute:
      AuthenticatedDashboardCurrentAffairsRouteWithChildren,
    AuthenticatedDashboardExamAlertsRoute:
      AuthenticatedDashboardExamAlertsRoute,
    AuthenticatedDashboardMockTestsRoute: AuthenticatedDashboardMockTestsRoute,
    AuthenticatedDashboardOverviewRoute: AuthenticatedDashboardOverviewRoute,
    AuthenticatedDashboardPreviousYearPapersRoute:
      AuthenticatedDashboardPreviousYearPapersRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardRankRoute: AuthenticatedDashboardRankRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardTestSeriesIdRoute:
      AuthenticatedDashboardTestSeriesIdRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedResultAttemptIdRoute: typeof AuthenticatedResultAttemptIdRoute
  AuthenticatedTestTestIdRoute: typeof AuthenticatedTestTestIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedResultAttemptIdRoute: AuthenticatedResultAttemptIdRoute,
  AuthenticatedTestTestIdRoute: AuthenticatedTestTestIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminDashboardRouteChildren {
  AdminDashboardCategoriesRoute: typeof AdminDashboardCategoriesRoute
  AdminDashboardCurrentAffairsRoute: typeof AdminDashboardCurrentAffairsRoute
  AdminDashboardMediaRoute: typeof AdminDashboardMediaRoute
  AdminDashboardNotificationsRoute: typeof AdminDashboardNotificationsRoute
  AdminDashboardPagesRoute: typeof AdminDashboardPagesRoute
  AdminDashboardProfileRoute: typeof AdminDashboardProfileRoute
  AdminDashboardQuestionsRoute: typeof AdminDashboardQuestionsRoute
  AdminDashboardReportsRoute: typeof AdminDashboardReportsRoute
  AdminDashboardSettingsRoute: typeof AdminDashboardSettingsRoute
  AdminDashboardTestSeriesRoute: typeof AdminDashboardTestSeriesRoute
  AdminDashboardTestsRoute: typeof AdminDashboardTestsRoute
  AdminDashboardUsersRoute: typeof AdminDashboardUsersRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardCategoriesRoute: AdminDashboardCategoriesRoute,
  AdminDashboardCurrentAffairsRoute: AdminDashboardCurrentAffairsRoute,
  AdminDashboardMediaRoute: AdminDashboardMediaRoute,
  AdminDashboardNotificationsRoute: AdminDashboardNotificationsRoute,
  AdminDashboardPagesRoute: AdminDashboardPagesRoute,
  AdminDashboardProfileRoute: AdminDashboardProfileRoute,
  AdminDashboardQuestionsRoute: AdminDashboardQuestionsRoute,
  AdminDashboardReportsRoute: AdminDashboardReportsRoute,
  AdminDashboardSettingsRoute: AdminDashboardSettingsRoute,
  AdminDashboardTestSeriesRoute: AdminDashboardTestSeriesRoute,
  AdminDashboardTestsRoute: AdminDashboardTestsRoute,
  AdminDashboardUsersRoute: AdminDashboardUsersRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CurrentAffairsRouteChildren {
  CurrentAffairsIdRoute: typeof CurrentAffairsIdRoute
}

const CurrentAffairsRouteChildren: CurrentAffairsRouteChildren = {
  CurrentAffairsIdRoute: CurrentAffairsIdRoute,
}

const CurrentAffairsRouteWithChildren = CurrentAffairsRoute._addFileChildren(
  CurrentAffairsRouteChildren,
)

interface ExamsRouteChildren {
  ExamsSlugRoute: typeof ExamsSlugRoute
}

const ExamsRouteChildren: ExamsRouteChildren = {
  ExamsSlugRoute: ExamsSlugRoute,
}

const ExamsRouteWithChildren = ExamsRoute._addFileChildren(ExamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutUsRoute: AboutUsRoute,
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRouteWithChildren,
  CurrentAffairsRoute: CurrentAffairsRouteWithChildren,
  ExamInfoRoute: ExamInfoRoute,
  ExamsRoute: ExamsRouteWithChildren,
  PagesSlugRoute: PagesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
